repos:
  - repo: ../../../gfx-automation-tools
    rev: e7cab35
    hooks:
      - id: file-extension-to-lowercase
      - id: check-shader-includes
      - id: format-code
      - id: check-branch-name
        stages: [push]
