repos:
  - repo: git@github.cds.internal.unity3d.com:theo-penavaire/gfx-automation-tools.git
    rev: b49459e
    hooks:
      - id: file-extension-to-lowercase
      - id: check-shader-includes
      - id: format-code
      - id: check-branch-name
        stages: [push]
